# Generated by Django 5.0 on 2023-12-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rfid", "0003_alter_rfidcard_card_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("card_number", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("entry_time", models.TimeField()),
                ("leave_time", models.TimeField()),
                ("stay_time", models.DurationField()),
            ],
        ),
    ]
