# Generated by Django 5.0 on 2023-12-21 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rfid", "0004_dailylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_time", models.DateTimeField()),
                ("leave_time", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rfid.userinfo"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DailyLog",
        ),
    ]
