# Generated by Django 5.0 on 2023-12-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rfid", "0005_userlog_delete_dailylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlog",
            name="stay_time",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
