# Generated by Django 5.0 on 2023-12-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rfid", "0006_userlog_stay_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="contact",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="department",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
